#if !canImport(ObjectiveC)
import XCTest

extension SlackLogHandlerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SlackLogHandlerTests = [
        ("testCritical", testCritical),
        ("testError", testError),
        ("testInfo", testInfo),
        ("testMetadata", testMetadata),
        ("testSendingRealMessageIfConfigured", testSendingRealMessageIfConfigured),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SlackLogHandlerTests.__allTests__SlackLogHandlerTests),
    ]
}
#endif
