#if !canImport(ObjectiveC)
import XCTest

extension ColorSchemeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ColorSchemeTests = [
        ("testColor", testColor),
    ]
}

extension IconTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IconTests = [
        ("testEmoji", testEmoji),
        ("testURL", testURL),
    ]
}

extension SlackLogHandlerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SlackLogHandlerTests = [
        ("testCritical", testCritical),
        ("testError", testError),
        ("testInfo", testInfo),
        ("testMetadata", testMetadata),
        ("testSendingRealMessageIfConfigured", testSendingRealMessageIfConfigured),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ColorSchemeTests.__allTests__ColorSchemeTests),
        testCase(IconTests.__allTests__IconTests),
        testCase(SlackLogHandlerTests.__allTests__SlackLogHandlerTests),
    ]
}
#endif
